import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";

import localFont from 'next/font/local';

const inter = Inter({ subsets: ['latin'], variable: '--font-sans' });

const openSauceFont = localFont({
  src: './fonts/OpenSauceSans-Bold.woff2',
  variable: '--font-open-sauce',
  display: 'swap',
});

export const metadata = {
  title: "EventSports",
  description: "Generated by create next app",
};

import { Providers } from "./providers";
import { Toaster } from "@/components/ui/toast";
import { ThemeProvider } from "@/context/ThemeContext";

export default function RootLayout({ children }) {
  return (
    <html
      lang="es"
      className={cn(
        "h-full antialiased dark scrollbar-thumb-accent font-sans",
        inter.variable,
        openSauceFont.variable
      )}
    >
      <body className="min-h-full flex flex-col overflow-x-hidden relative">
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <Providers>
            {children}
          </Providers>
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  );
}