import { Bebas_Neue, Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";

const inter = Inter({ subsets: ['latin'], variable: '--font-sans' });

const bebasNeue = Bebas_Neue({
  variable: "--font-bebas",
  subsets: ["latin"],
  weight: "400",
});

export const metadata = {
  title: "EventSports",
  description: "Generated by create next app",
};

import { Providers } from "./providers";

export default function RootLayout({ children }) {
  return (
    <html
      lang="es"
      className={cn("h-full", "antialiased", "dark", bebasNeue.variable, "font-sans", inter.variable)}
    >
      <body className="min-h-full flex flex-col overflow-x-hidden relative">
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}